from __future__ import annotations

from pathlib import Path

from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer


def build_pitch_pdf(output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    doc = SimpleDocTemplate(str(output_path), pagesize=LETTER)
    styles = getSampleStyleSheet()

    story = []
    story.append(Paragraph("DutyGuard AI – First Customer Pitch Pack", styles["Title"]))
    story.append(Spacer(1, 12))

    sections = [
        (
            "1) Positioning",
            "DutyGuard helps importers identify recoverable overpaid duties, prioritize claims by impact, and route high-risk decisions to human review.",
        ),
        (
            "2) The Offer",
            "Free 50–100 entry tariff leakage assessment, then paid pilot with contingency-based economics tied to validated recovery outcomes.",
        ),
        (
            "3) What to Say on Calls",
            "We provide a transparent, auditable workflow: confidence scores, review reasons, legal citations, and claim-ready packets. High-risk items are never auto-finalized.",
        ),
        (
            "4) What to Demo",
            "Onboard entries, show Top 10 recoverable opportunities, open review queue, classification report, claim packet export, and metrics dashboard.",
        ),
        (
            "5) 2-Week Sprint",
            "Week 1: trust and safety controls. Week 2: pilot execution, prioritized opportunities, and proof artifacts with before/after deltas.",
        ),
        (
            "6) Legal Guardrails",
            "Decision support only. Final customs/legal determinations require qualified human professionals.",
        ),
        (
            "7) Practical Close",
            "Ask for one warm intro, run free audit, present ranked opportunities, convert to 30–60 day pilot, and convert results into first case study.",
        ),
    ]

    for heading, body in sections:
        story.append(Paragraph(heading, styles["Heading2"]))
        story.append(Paragraph(body, styles["BodyText"]))
        story.append(Spacer(1, 10))

    story.append(Paragraph("Generated by DutyGuard AI scripts/generate_customer_pitch_pdf.py", styles["Italic"]))

    doc.build(story)


if __name__ == "__main__":
    project_root = Path(__file__).resolve().parents[1]
    output_pdf = project_root / "docs" / "DutyGuard_First_Customer_Pitch.pdf"
    build_pitch_pdf(output_pdf)
    print(f"Created: {output_pdf}")
